<?php

namespace Controller;

use \W\Controller\Controller;

class DefaultController extends Controller {


    public function show($file, array $data = array())
    {
        $category = new \Model\CategoriesModel();
        $data['categories'] = $category->getCategories();
        parent::show($file, $data); // TODO: Change the autogenerated stub
    }

	//DEFAULT HOMEPAGE
	public function home() {
		$this->show('default/home');
	}

	public function conditionGeneral(){
        $this->show('default/condition-general');
    }


}