<?php

namespace Controller;

use \W\Controller\Controller;

class DefaultController extends Controller {

    protected $nbElements = 2;


    public function show($file, array $data = array())
    {
        $category = new \Model\CategoriesModel();
        $data['categories'] = $category->getCategories();
        parent::show($file, $data); // TODO: Change the autogenerated stub
    }

    public function showNotFound() {

        $file = self::PATH_VIEWS.'/w_errors/404.php';

        if(file_exists($file)) {
            $this->show('w_errors/404');
        } else {
            die('404');
        }
    }

	//DEFAULT HOMEPAGE
	public function home() {

		$this->show('default/home');
	}

	public function conditionGeneral(){
        $this->show('default/condition-general');
    }

    public function confidentialite(){
	    $this->show('default/confidentialite');
    }


}